name: auto_validate
description: The Auto Validate package streamlines input validation by leveraging customizable regular expressions, allowing for efficient verification of various data formats.
version: 3.0.7
homepage: https://github.com/dev-mahmoud-elshenawy/auto_validate
repository: https://github.com/dev-mahmoud-elshenawy/auto_validate
issue_tracker: https://github.com/dev-mahmoud-elshenawy/auto_validate/issues
license: MIT

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
